version: '3.6'

services:

  sc10:
    build: .
    image: docker-se.glue.ch/znueni:1.0.0
    container_name: c10
    #network_mode: bridge
    networks:
    #  default:
      pingpong-1:
        aliases: 
          - c10.ch
    stop_signal: SIGKILL
    ports:
      - "8010:8080"

  sc11:
    image: docker-se.glue.ch/znueni:1.0.0
    container_name: c11
    #network_mode: bridge
    networks:
    #  default:
      pingpong-1:
        aliases: 
          - c11.ch
    stop_signal: SIGKILL
    ports:
      - "8011:8080"
    depends_on:
      - sc10

networks:
  pingpong-1:
    name: pingpong-1
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.1.1.0/16
#  default:
#    external:
#      name: bridge
#      name: pingpong-1
