version: '3.6'

services:

  sc10:
    build: .
    image: docker-se.glue.ch/pingpong:1.0.0
    container_name: c10
    networks:
      pingpong-1:
        aliases: 
          - c10.ch
    volumes:
      - type: bind
        source: ./second
        target: /pingpong/second
        read_only: true
      - type: bind
        source: $PWD/src/main/java
        target: /pingpong/java
        read_only: true
      - type: bind
        source: $HOME/workspace/juspace/test
        target: /pingpong/juspace/test
        read_only: true
    stop_signal: SIGKILL
    ports:
      - "8010:8080"

  sc11:
    image: docker-se.glue.ch/pingpong:1.0.0
    container_name: c11
    networks:
      pingpong-1:
        aliases: 
          - c11.ch
    stop_signal: SIGKILL
    ports:
      - "8011:8080"
    depends_on:
      - sc10

networks:
  pingpong-1:
    name: pingpong-1
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.1.1.0/16
