version: '3.5'

services:

  sc12:
    build: .
    image: docker-se.glue.ch/pingpong:1.0.0
    container_name: c12
    networks:
      pingpong-1:
        aliases: 
          - c12.ch
    stop_signal: SIGKILL
    ports:
      - "8012:8080"

  sc13:
    image: docker-se.glue.ch/pingpong:1.0.0
    container_name: c13
    networks:
      pingpong-1:
        aliases: 
          - c13.ch
    stop_signal: SIGKILL
    ports:
      - "8013:8080"
    depends_on:
      - sc12

networks:
  pingpong-1:
    name: pingpong-1
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.10.0/24
