version: '3.6'

services:

  sc20:
    build: .
    image: docker-se.glue.ch/znueni:1.0.0
    container_name: c20
    #network_mode: bridge
    networks:
    #  default:
      pingpong-2:
        aliases: 
          - c20.ch
    stop_signal: SIGKILL
    ports:
      - "8020:8080"

  sc21:
    image: docker-se.glue.ch/znueni:1.0.0
    container_name: c21
    #network_mode: bridge
    networks:
    #  default:
      pingpong-2:
        aliases: 
          - c21.ch
    stop_signal: SIGKILL
    ports:
      - "8021:8080"
    depends_on:
      - sc20

networks:
  pingpong-2:
    name: pingpong-2
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.2.2.0/16
#  default:
#    external:
#      name: bridge
#      name: pingpong-2
