version: '3.6'

services:

  sc20:
    build: .
    image: docker-se.glue.ch/znueni:1.0.0
    container_name: c20
    #network_mode: bridge
    #networks:
    #  default:
    #    aliases: 
    #      - cont1.ch
    stop_signal: SIGKILL
    ports:
      - "8020:8080"

  sc21:
    image: docker-se.glue.ch/znueni:1.0.0
    container_name: c21
    #network_mode: bridge
    #networks:
    #  default:
    #    aliases: 
    #      - cont2.ch
    stop_signal: SIGKILL
    ports:
      - "8021:8080"
    depends_on:
      - sc20

networks:
  default:
    external:
      # name: bridge
      name: network-2
