version: '3.5'

services:

  sc22:
    build: .
    image: docker-se.glue.ch/pingpong:1.0.0
    container_name: c22
    networks:
      pingpong-2:
        aliases: 
          - c22.ch
    stop_signal: SIGKILL
    ports:
      - "8022:8080"

  sc23:
    image: docker-se.glue.ch/pingpong:1.0.0
    container_name: c23
    networks:
      pingpong-2:
        aliases: 
          - c23.ch
    stop_signal: SIGKILL
    ports:
      - "8023:8080"
    depends_on:
      - sc22

networks:
  pingpong-2:
    name: pingpong-2
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.20.0/24
